//? #version 430
#ifndef INCLUDE_CONSTANTS_GLSL
#define INCLUDE_CONSTANTS_GLSL

#define PTHREAD 512
#define CTHREAD 256
#define EPSILON 1e-6


// --- Domain ---
const vec3 domain = vec3(300, 200, 100);
const vec3 halfdomain = domain/2.0;
const vec3 boundaryMin = vec3(-domain.x/2.0 , -domain.y/2.0, 0);
const vec3 boundaryMax = vec3(domain.x / 2.0, domain.y / 2.0, domain.z);

const float particleRadius = 1;//mm
#endif