//? #version 430
#ifndef INCLUDE_BUFFERS_GLSL
#define INCLUDE_BUFFERS_GLSL

//Macro to access buffer
#define B_x(buffer_index) ssbo_position[buffer_index].xyz
#define B_v(buffer_index) ssbo_velocity[buffer_index].xyz

//Shortcuts
#define xi B_x(i).xyz
#define vi B_v(i).xyz

layout(std430) buffer position_buffer {
	vec4 ssbo_position[];
};

layout(std430) buffer velocity_buffer {
	vec4 ssbo_velocity[];
};

#endif// INCLUDE_BUFFERS_HLSL