//? #version 430
#ifndef INCLUDE_UNIFORMS_GLSL
#define INCLUDE_UNIFORMS_GLSL

uniform float restDensity = 1.0;//g/mm3
uniform float particleMass = 1.0;//g

uniform float dt = 0.005;//s
uniform float g = 9.81f*1000.0;//mm/s^-2

uniform float artificialPressureMultiplier = 0.0001;
uniform float artificialViscosityMultiplier = 0.0001;

uniform float stiffness = 5000000.0;
uniform uint numParticles = 0;
uniform bool stabilizationPass = false;

#endif